In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dim_course = pd.read_parquet('../data/bronze/parquet/dim_course.parquet')
dim_district = pd.read_parquet('../data/bronze/parquet/dim_district.parquet')
dim_university = pd.read_parquet('../data/bronze/parquet/dim_university.parquet')
dim_year = pd.read_parquet('../data/bronze/parquet/dim_year.parquet')
fact_cutoffs = pd.read_parquet('../data/bronze/parquet/fact_cutoffs.parquet')

In [10]:
# create dataframes for each file

course_df = pd.DataFrame(dim_course)
district_df = pd.DataFrame(dim_district)
university_df = pd.DataFrame(dim_university)
year_df = pd.DataFrame(dim_year)
fact_cutoffs_df = pd.DataFrame(fact_cutoffs)

In [15]:
course_df.head()

          CourseID                                     CourseName
0  COURSE_D5E20A1F                       AGRI BUSINESS MANAGEMENT
1  COURSE_6FB49258  AGRICULTURAL RESOURCE MANAGEMENT & TECHNOLOGY
2  COURSE_5EA0149E           AGRICULTURAL TECHNOLOGY & MANAGEMENT
3  COURSE_4173EF9E                                    AGRICULTURE
4  COURSE_E2281A76                                 ANIMAL SCIENCE

In [16]:
district_df.head()

          DistrictID DistrictName
0  DISTRICT_80F4B83B      COLOMBO
1  DISTRICT_40903503      GAMPAHA
2  DISTRICT_656E1CE3     KALUTARA
3  DISTRICT_A17237FA       MATALE
4  DISTRICT_3680DD41        KANDY

In [17]:
university_df.head()

          UniversityID                               UniversityName
0  UNIVERSITY_9536C93C      Eastern University - Trincomalee Campus
1  UNIVERSITY_AD9FA107       Eastern University -Trincomalee Campus
2  UNIVERSITY_E403C90A                Eastern University, Sri Lanka
3  UNIVERSITY_2BB005E6  Gampaha Wickramaarachchi Ayurveda Institute
4  UNIVERSITY_E4515AC8             Institute of Indigenous Medicine

In [23]:
# inspectiong unique universities

print("Unique Universities: \n", university_df['UniversityName'].unique())

Unique Universities:
 <ArrowStringArray>
[                                 'Eastern University - Trincomalee Campus',
                                   'Eastern University -Trincomalee Campus',
                                            'Eastern University, Sri Lanka',
                              'Gampaha Wickramaarachchi Ayurveda Institute',
                                         'Institute of Indigenous Medicine',
                                         'Rajarata University of Sri Lanka',
                                          'Ramanathan Academy of Fine Arts',
                                     'Sabaragamuwa University of Sri Lanka',
                                    'South Eastern University of Sri Lanka',
                         'Swami Vipulananda Institute of Aesthetic Studies',
                                                    'University of Colombo',
                                 'University of Colombo - Sri Palee Campus',
                                'University of Colombo School of Computing',
                                                     'University of Jaffna',
                                   'University of Jaffna - Vavuniya Campus',
                                                   'University of Kelaniya',
                                                   'University of Moratuwa',
                                                 'University of Peradeniya',
                                                     'University of Ruhuna',
                                        'University of Sri Jayewardenepura',
                               'University of the Visual & Performing Arts',
                                     'Uva Wellassa University of Sri Lanka',
                                          'Wayamba University of Sri Lanka',
 'The Gampaha Wickramarachchi University of Indigenous Medicine, Sri Lanka',
                                        'University of Vavuniya, Sri Lanka',
                                            'University of Jayewardenepura',
                                               'University of Sabaragamuwa',
                                                            'HONOURS) (BIS',
                                                                      'ICT',
                                                                     'TMLE',
                     'The Gampaha Wickramarachchi University of Indigenous',
               'Gampaha Wickramarachchi University of Indigenous Medicine,',
                        'Trincomalee Campus, Eastern University, Sri Lanka']
Length: 33, dtype: str

In [18]:
year_df.head()

           YearID AcademicYear  ExamYear PublicationDate
0  YEAR_2025_2026    2025/2026      2025      2026-07-31

In [19]:
fact_cutoffs_df.head()

,AcademicYear,ExamYear,PublicationDate,CourseID,CourseName,UniversityID,UniversityName,DistrictID,DistrictName,CutoffZ,CutoffStatus,AllIslandMerit,AptitudeTest,Page,SourceFile
0,2025/2026,2025,2026-07-31,COURSE_D5E20A1F,AGRI BUSINESS MANAGEMENT,UNIVERSITY_E728A0EF,University of Ruhuna,DISTRICT_8F1646E1,AMPARA,1.4932,AVAILABLE,False,False,6,COP_2018_2019.pdf
1,2025/2026,2025,2026-07-31,COURSE_D5E20A1F,AGRI BUSINESS MANAGEMENT,UNIVERSITY_E728A0EF,University of Ruhuna,DISTRICT_B94F4CB8,ANURADHAPURA,1.5161,AVAILABLE,False,False,6,COP_2018_2019.pdf
2,2025/2026,2025,2026-07-31,COURSE_D5E20A1F,AGRI BUSINESS MANAGEMENT,UNIVERSITY_E728A0EF,University of Ruhuna,DISTRICT_0E1A9D59,BADULLA,1.4155,AVAILABLE,False,False,6,COP_2018_2019.pdf
3,2025/2026,2025,2026-07-31,COURSE_D5E20A1F,AGRI BUSINESS MANAGEMENT,UNIVERSITY_E728A0EF,University of Ruhuna,DISTRICT_52F9214F,BATTICALOA,NaN,NQC,False,False,6,COP_2018_2019.pdf
4,2025/2026,2025,2026-07-31,COURSE_D5E20A1F,AGRI BUSINESS MANAGEMENT,UNIVERSITY_E728A0EF,University of Ruhuna,DISTRICT_80F4B83B,COLOMBO,1.3972,AVAILABLE,False,False,6,COP_2018_2019.pdf

In [21]:
# inspecting unique academic years

print("Unique Academic Years:", year_df['AcademicYear'].unique())
print("Unique Exam Years:", year_df['ExamYear'].unique())

Unique Academic Years: <ArrowStringArray>
['2025/2026']
Length: 1, dtype: str
Unique Exam Years: [2025]